### ISSUE TITLE
View.propTypes is removed in last RN version

### ISSUE THREAD

**Issue by sytolk** [ksti/react-native-star-rating-view#2]
`ReactNativeJS: undefined is not an object (evaluating '_react3.default.PropTypes.bool')`

If it's need back compatibality:
https://github.com/react-community/react-native-maps/pull/1474/files

**Comment by Tiago-Marques** [comment]
Hello, it's easy to fix that. I'm opening a pull request to be accepted.

**Comment by Tiago-Marques** [comment]
Pull request opened (:

**Comment by ksti** [comment]
@sytolk this would be a nice way to fix that. Thank you very much! :)

**Comment by sytolk** [comment]
@ksti I can confirm that "react-native-star-rating-view": "^0.0.10" works with RN: 
        "react": "16.0.0-beta.5",
        "react-native": "0.49.5",
but after fix of missing import here: https://github.com/ksti/react-native-star-rating-view/commit/234f2a1c5764155fec2e716a3e176e439d9e5cff#r26763533
