### ISSUE TITLE
The rating bar shows incorrect rating until the flatlist is scrolled in IOS.

### ISSUE THREAD

**Issue by tayguohong** [ksti/react-native-star-rating-view#7]
I am facing this issue when I implement this component within a flatlist. 
<img width="261" alt="Screenshot 2019-12-11 at 2 49 05 PM" src="https://user-images.githubusercontent.com/57252173/70598333-8fca7800-1c25-11ea-9eb3-9b5411ff1f36.png">
The image above shows the incorrect rating of the star. Any solution to solve this issue?

**Comment by ksti** [comment]
Sorry for late reply，I will try it soon.

**Comment by ksti** [comment]
@tayguohong I cannot reproduce this issue, can you provide a simple demo for it? Is this issue on android? I think maybe you can try it in release mode, or upgrade the version of react-native, did you have solved this issue?
![Simulator Screen Shot - iPhone 11 - 2020-04-03 at 16 46 22](https://user-images.githubusercontent.com/8263831/78343931-2b656700-75ce-11ea-8640-621159c8d111.png)

**Comment by tayguohong** [comment]
@ksti I didn't face this issue on android platform. I cannot solve this issue, so i use other library in iOS platform. As for the demo code, I will try to post here asap when i am free.

**Comment by tayguohong** [comment]
@ksti Here is the demo code. Sorry for late reply. 
`import React, { Component } from "react"
import {
    View,
    StyleSheet,
    FlatList,
    TouchableOpacity,
    Image
} from "react-native"
import StarRatingBar from 'react-native-star-rating-view/StarRatingBar'
import MatIcon from "react-native-vector-icons/MaterialCommunityIcons"
import Text from '../components/Text'

export default class StarRatingTesting extends Component {
    constructor(props) {
        super(props);

        this.state = {
            jobList: []
        }
    }
    componentDidMount() {
        this.loadData()
    }
    loadData() {
        const ENTRIES1 = [
            {
                id: 1,
                jobImage: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png",
                jobPosition: "Barista",
                outlet: "KLCC Third Floor",
                shopName: "Starbucks",
                location: "Kuala Lumpur",
                workingDays: "S S",
                workingTime: "18:00 - 22:00",
                wages: "RM 10 per hour",
                rating: 4.7,
                review: 200
            },
            {
                id: 2,
                jobImage: "https://thebrewhouse.my/wp-content/themes/thebrewhouse/images/logo-wc-b.png",
                jobPosition: "Cashier",
                outlet: "Puchong Jaya",
                shopName: "The Brew House",
                location: "Puchong",
                workingDays: "F S S",
                workingTime: "12:00 - 21:00",
                wages: "RM 15 per hour",
                rating: 2.5,
                review: 60

            },
            {
                id: 3,
                jobImage: "https://1000logos.net/wp-content/uploads/2017/08/Domino%E2%80%99s-Emblem.jpg",
                jobPosition: "Barista",
                outlet: "Pandan Jaya",
                shopName: "Domino's Pizza",
                location: "Cheras",
                workingDays: "M T W",
                workingTime: "18:00 - 22:00",
                wages: "RM 12 per hour",
                rating: 5.0,
                review: 0

            },
            {
                id: 4,
                jobImage: "https://media-cdn.tripadvisor.com/media/photo-s/06/cf/bc/49/moonlight-cafe.jpg",
                jobPosition: "Kitchen Helper",
                outlet: "Puchong Jaya",
                shopName: "Moonlight Cake House",
                location: "Puchong",
                workingDays: "S S",
                workingTime: "12:00 - 22:00",
                wages: "RM 17 per hour",
                rating: 4.5,
                review: 55

            },
            {
                id: 5,
                jobImage: "https://upload.wikimedia.org/wikipedia/ms/4/43/Marrybrown_Logo.png",
                jobPosition: "Barista",
                outlet: "Melawati Mall",
                shopName: "Marrybrown",
                location: "Kuala Lumpur",
                workingDays: "S S",
                workingTime: "18:00 - 22:00",
                wages: "RM 10 per hour",
                rating: 4.2,
                review: 30

            }
        ];
        this.setState({ jobList: ENTRIES1 })
    }
    _renderItem = ({ item }) => {
        return (
            <TouchableOpacity style={styles.slider}
                activeOpacity={1}
                // onPress={this._navigateToListItem.bind(this, item.id)}
                >

                <View style={styles.outer}>

                    <Image style={styles.imageStyle}
                        source={{ uri: item.jobImage }}>

                    </Image>

                    <View style={styles.secondContainer}>
                        <View style={styles.truncateContainer}>
                            <Text style={styles.jobPostText}
                            // numberOfLines={1}
                            >
                                {item.jobPosition}
                            </Text>
                            <Text style={styles.outletText}>
                                {"(" + item.outlet + ")"}
                            </Text>
                        </View>
                        <View style={styles.truncateContainer}>
                            <Text style={styles.shopNameText}
                            // numberOfLines={1}
                            >
                                {item.shopName}
                            </Text>
                        </View>
                        <View style={styles.truncateContainer}>
                            <MatIcon style={styles.pinIcon}
                                name="pin"
                                size={20}
                            />
                            <Text style={styles.locationText}
                                numberOfLines={1}>
                                {item.location}
                            </Text>
                        </View>
                        <View style={styles.truncateContainer}>
                            <MatIcon style={styles.calendarIcon}
                                name="calendar"
                                size={20}
                            />
                            <Text style={styles.daysText}
                                numberOfLines={1}
                            >
                                {item.workingDays}
                            </Text>
                        </View>
                        <View style={styles.truncateContainer}>
                            <MatIcon style={styles.clockIcon}
                                name="alarm"
                                size={20}
                            />
                            <Text style={styles.workingHoursText}
                                numberOfLines={1}>
                                {item.workingTime}

                            </Text>
                        </View>
                        <View style={styles.truncateContainer}>
                            <MatIcon style={styles.clockIcon}
                                name="currency-usd"
                                size={20}
                            />
                            <Text style={styles.wagesText}
                                numberOfLines={1}
                            >
                                {item.wages}
                            </Text>
                        </View>
                        <View style={styles.thirdContainer}>
                            <Text style={styles.ratingText}>
                                {item.rating}
                            </Text>
                            <StarRatingBar
                                style={styles.starRatingStyle}
                                // starStyle={{
                                //     width: 15,
                                //     height: 15,
                                //     // flex: 1
                                // }}
                                score={item.rating}
                                dontShowScore={true} // true: not show the score text view
                                allowsHalfStars={true}
                                spacing={3}
                                continuous={false}
                                accurateHalfStars={true}
                            />
                            <Text style={styles.reviewText}>
                                {item.review + " " + "reviews"}
                            </Text>

                        </View>

                    </View>
                </View>
            </TouchableOpacity>
        );
    }
    render() {
        return (
            <View style={styles.container}>
                <FlatList
                    data={this.state.jobList}
                    renderItem={this._renderItem}>

                </FlatList>

            </View>
        )
    }
}
const styles = StyleSheet.create({
    container: {
        flex: 1
    },
    truncateContainer: {
        flexDirection: "row"
    },
    outer: {
        // flex: 1,
        backgroundColor: "white",
        borderWidth: 1,
        borderRadius: 10,
        borderColor: "#696969",
        flexDirection: "column",
        // padding: 10,
        marginTop: 10,
        marginBottom: 10,
        marginLeft: 10,
        marginRight: 10
    },
    imageStyle: {
        width: "100%",
        height: 100,
        borderTopLeftRadius: 9,
        borderTopRightRadius: 9
    },
})`

The star rating on iOS platform shows 0 rating initially. After scrolling, then it shows the correct rating. In android, the rating is correct from the beginning .

**Comment by ksti** [comment]
@tayguohong  I have run the demo code, but still not see that issue.
Here is my `react-native info`

## React Native version:
```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.15.3
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 293.86 MB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v10.9.0/bin/yarn
      npm: 6.8.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.0 => 0.59.10
```


![截屏2020-04-21上午10 36 39](https://user-images.githubusercontent.com/8263831/79819861-7c8e9c80-83bd-11ea-88e5-2ae84fe2903d.png)

**Comment by ksti** [comment]
@tayguohong Could I use your code in the demo?

**Comment by tayguohong** [comment]
@ksti sure you can. Here is the screenshot of my issue
<img width="337" alt="Screenshot 2020-04-21 at 11 09 01 AM" src="https://user-images.githubusercontent.com/57252173/79821263-e197c180-83c0-11ea-90d3-4be05e739c00.png">
.

**Comment by ksti** [comment]
@tayguohong ok, this seem to be a problem of FlatList, updating the version of react-native should solved this issue. Or you can try specify a key property on each item of FlatList as react-native suggested: `VirtualizedList: missing keys for items, make sure to specify a key property on each  item or provide a custom keyExtractor.`

**Comment by tayguohong** [comment]
> @tayguohong ok, this seem to be a problem of FlatList, updating the version of react-native should solved this issue. Or you can try specify a key property on each item of FlatList as react-native suggested: `VirtualizedList: missing keys for items, make sure to specify a key property on each item or provide a custom keyExtractor.`

Okay. Since there is no problem when you running my demo code, then there is high chances to be an issue from Flatlist. Currently I am still using other library for iOS platform. My current react-native version is 0.60.4 now. Thank you again for providing this library. I am closing this issue now.
